service: backend-miranda-node
frameworkVersion: "3"
provider:
  name: aws
  region: eu-west-1
  environment:
    SECRET_KEY: ${file(.env.json):SECRET_KEY}
  runtime: nodejs18.x
functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY